### ISSUE TITLE
No way to select fixes through the main window

### ISSUE THREAD

**Issue by David-Else** [davidlday/vscode-languagetool-linter#120] opened 2020-04-25 14:38 UTC
Currently errors are underlined yellow, but when the cursor is placed on them there is no lightbulb to click to fix it as other extensions supply. Also, VS Code says fox example:
```
SENT_START_CONJUNCTIVE_LINKING_ADVERB_COMMA: Did you forget a comma after a conjunctive/linking adverb?
Peek Problem (Alt+F8)
Quick Fix... (Ctrl+.)
```
Peek does nothing (as expected), but when I select quick fix there is nothing there. This is essential for keyboard use.

The only way to use this tool seems to be going error by error through the 'problems' menu where the fixes are provided and I can click them. Is this a bug?

I have downloaded languagetool from their site and run:
```
java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8081
```
Is this correct? I can't find anything in the docs about downloading the code from the site for Linux, only homebrew.

The extension connects OK, but there seems to be an 8 second delay on everything making it unusable. I looked at the 'managed jar file' option, but it says that option is `DEPRECIATED`. I am on Linux, what is the best way to set this up?

The tool looks amazing, hope I can get it working! Here is what the terminal looks like:
![Screenshot from 2020-04-25 15-40-11](https://user-images.githubusercontent.com/12832280/80282822-6eb58000-870b-11ea-95e6-790ea34c1b1d.png)

**Comment by davidlday** [comment] 2020-04-26 13:43
@David-Else - Thank you for the feedback. Very helpful.

> The only way to use this tool seems to be going error by error through the 'problems' menu where the fixes are provided and I can click them. Is this a bug?

Yes, this is a bug. Definitely meant to be used like any other linter in VS Code.

* Peek should show the message, and is showing for me when I click it. I have to hover over the error for the tooltip box to show up, then I can click on "Peek Problem" or "Quick Fix...". However, neither keyboard shortcut seems to work.
* `ctl+.` should bring up the actions. I have verified it isn't.
* The light bulb should show up for each error. I have verified it isn't.

A few questions:

* What OS / version are you on?
* What version of VS Code are you using?

As for how you run, yes, that's all there is to it for using locally. I updated the wiki to point back to the [official instructions](http://wiki.languagetool.org/http-server).

**Comment by davidlday** [comment] 2020-04-26 13:49
@David-Else - One more quick note. 

Use "Class Path" instead of "Jar File".

They essentially work the same way. I had to change because some platforms (Arch Linux, at least) don't install a single JAR, but several. "Jar File" only take a path to a single JAR; "Class Path" will accept directories and JAR files, and add them all to the class path.

**Comment by David-Else** [comment] 2020-04-26 13:53
Hello,
```shell
code --version
1.44.2
```
OS is Centos 8.1 (if you have not used it, it is almost the same as Fedora).

Any idea what the 8 second delay could be, any more info I could provide to help with that? Cheers.

**Comment by David-Else** [comment] 2020-04-26 14:03
Here is a screenshot hovering over 'Dahl'. Also, is it possible to remove `MORFOLOGIK_RULE_EN_US` from appearing everywhere? Cheers.
![Screenshot from 2020-04-26 15-00-27](https://user-images.githubusercontent.com/12832280/80309773-e7c9db80-87ce-11ea-9498-da1345fcac9e.png)

**Comment by David-Else** [comment] 2020-04-26 14:08
I have just found that if I click the quick fix I get actions to take, but it I press ctrl + . it says no code actions available:
![Screenshot from 2020-04-26 15-07-33](https://user-images.githubusercontent.com/12832280/80309900-bd2c5280-87cf-11ea-8419-1aa88fe9a37c.png)
![Screenshot from 2020-04-26 15-07-16](https://user-images.githubusercontent.com/12832280/80309901-bdc4e900-87cf-11ea-8d8a-85139e61f792.png)

**Comment by davidlday** [comment] 2020-04-26 16:16
Okay - thanks for the additional info and verifying this is a bug.

> Also, is it possible to remove MORFOLOGIK_RULE_EN_US from appearing everywhere? Cheers.

I think so. I'll open a separate issue for it since it would be an enhancement instead of part of this bug.

**Comment by davidlday** [comment] 2020-05-05 12:40
I think I've found the problem but may take another week to fix it. In the meantime, if you highlight the entire range of the error, you should get the light bulb to show up. For instance, if a word is misspelled, double-click to highlight the whole word, and you'll get the light bulb.

Also, my apologies - I missed your previous question about an 8-second delay. First thing is figuring out if it's in the extension or the server. Would you mind testing using the public LanguageTool API? Make sure you're not running the server locally, and reconfigure the extension to use the "public" service type. Let me know if you still see a delay.

**Comment by David-Else** [comment] 2020-05-05 13:22
Hi, thanks for getting back. I have found that the delay was because my MD file was very long, with shorter files the delay was much smaller, so I don't think it is a server issue.

Great news we can expect a fix. My goal is to only use a keyboard to prevent RSI problems, so I can't be clicking on anything to select whole words. I am using the neo-vim/vscode plugin https://github.com/asvetliakov/vscode-neovim , so that complicates things a bit.

There is no hurry on my part for the fix at this point as I am only grammar checking at the end of the job and can use the libre office extension for now. Cheers!

**Comment by dflock** [comment] 2021-02-05 02:05
This still doesn't work for me, sadly.

VSCode version:
```
Version: 1.53.0-insider
Commit: e1c818a171168eedf78b62fdc7f4e3458d5dea7c
Date: 2021-02-03T08:25:21.292Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-58-generic
```

LanguageTool Linter Version: v0.17.0
LanguageTool Server Version: 5.2 (released 2020-12-29)
LanguageTool Server startup:

```
java -cp ~/bin/LanguageTool-5.2/languagetool-server.jar org.languagetool.server.HTTPServer --port 28081 --allow-origin "*" --languageModel /var/tmp/dunc_scratch/LanguageTool
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
2021-02-04 17:25:49 -0800 INFO  org.languagetool.server.DatabaseAccess Not setting up database access, dbDriver is not configured
2021-02-05 01:25:49 +0000 WARNING: running in HTTP mode, consider running LanguageTool behind a reverse proxy that takes care of encryption (HTTPS)
2021-02-05 01:25:50 +0000 Setting up thread pool with 10 threads
2021-02-05 01:25:50 +0000 Starting LanguageTool 5.2 (build date: 2020-12-29 15:54, eb572bf) server on http://localhost:28081...
2021-02-05 01:25:50 +0000 Server started
```

LanguageTool server is running locally and works - i.e. provides suggestions to VSCode and the browser & LibreOffice plugins are using it fine.

I just don't get and quick fix or light bulbs on errors in VSCode.

**Comment by davidlday** [comment] 2021-02-08 02:13
Reopening to investigate.

**Comment by dflock** [comment] 2021-02-08 06:10
What can I do to help figure this out?

**Comment by davidlday** [comment] 2021-02-10 11:40
@dflock - thanks for the offer, and for the details. I'm not entirely sure how you can help, but I'll let you know. I may not get a chance to assess the situation until this weekend.

@David-Else - are you still experiencing this problem?

**Comment by davidlday** [comment] 2021-02-10 11:47
@dflock - actually, can you post a screenshot of the diagnostic for a spelling error and for a non-spelling error (i.e. [Successive sentences beginning with the same word](https://community.languagetool.org/rule/show/ENGLISH_WORD_REPEAT_BEGINNING_RULE?lang=en)). Not all diagnostics will have code actions. Spelling errors definitely should, and the Successive Sentences rule definitely should not.

**Comment by David-Else** [comment] 2021-02-10 12:02
@davidlday Afraid I don't use this extension anymore so can't help, I still hope it gets fixed :)

**Comment by dflock** [comment] 2021-02-11 08:04
![Screenshot_2021-02-11_00-03-17](https://user-images.githubusercontent.com/47756/107613191-a6d77200-6bfc-11eb-8619-8f3c24fef410.png)
![Screenshot_2021-02-11_00-03-04](https://user-images.githubusercontent.com/47756/107613195-a7700880-6bfc-11eb-9f01-a60d2330a6c6.png)

**Comment by davidlday** [comment] 2021-02-11 12:39
@dflock - Am I right in assuming you're using `en-CA` for Language / Mother Tongue settings?

I think the second rule (ENGLISH_WORD_REPEAT_BEGINNING_RULE) has no quick fixes because the LanguageTool made no suggestions on how to fix it. I'll have to test. Will post when I know more.

**Comment by dflock** [comment] 2021-02-11 20:18
I have it set like this:

![image](https://user-images.githubusercontent.com/47756/107693273-c1443680-6c62-11eb-8a59-b36ee1007d32.png)

I set it like this because I'm originally British and live in Canada now, but I don't really know what this setting does - how should it be set?

When I saved that text file, this was the console output from the languagetool server:

```
detected en using built-in in 0.39ms for 109 chars
2021-02-11 12:16:58 -0800 INFO  org.languagetool.server.TextChecker Check done: 109 chars, en-CA (mother tongue: en-GB), #30, null, 3 matches, 143ms, agent:-, sent, q:0, h:1, dH:1, m:all
```

this is the text:

```
Moreover, the street is almost entirely residential. Moreover, it was named after a poet
This is spalld rong.
111

**Comment by davidlday** [comment] 2021-02-11 23:40
The Mother Tongue just enables another set of possible rules, but I don't think it's critical or would have any affect here. I'm not able to reproduce the problem yet. Here's what I'm seeing. I know it doesn't help yet, but we'll get there.

![Screen Shot 2021-02-11 at 6 39 31 PM](https://user-images.githubusercontent.com/1132144/107713116-8fe65d80-6c98-11eb-8d7f-91056951f6c5.png)

Set my language / mother tongue to match yours.

![Screen Shot 2021-02-11 at 6 30 06 PM](https://user-images.githubusercontent.com/1132144/107712542-96280a00-6c97-11eb-8050-a82c4b52abfd.png)

Errors are correctly identified.

![Screen Shot 2021-02-11 at 6 30 16 PM](https://user-images.githubusercontent.com/1132144/107712551-9d4f1800-6c97-11eb-9003-14c1a4878254.png)

No quick fix for ENGLISH_WORD_REPEAT_BEGINNING_RULE, which is expected.

![Screen Shot 2021-02-11 at 6 30 33 PM](https://user-images.githubusercontent.com/1132144/107712560-9fb17200-6c97-11eb-8cfa-19b73a0e6f95.png)

Quick fix shows for spelling (notice EN_CA), which is expected.

![Screen Shot 2021-02-11 at 6 30 45 PM](https://user-images.githubusercontent.com/1132144/107712577-a4762600-6c97-11eb-9977-a86fc75fe229.png)

Long list of suggested corrections, which is expected.

![Screen Shot 2021-02-11 at 6 30 52 PM](https://user-images.githubusercontent.com/1132144/107712580-a7711680-6c97-11eb-97a4-02e63c8143dc.png)

LanguageTool log showing similar output to yours above.

Again, doesn't fix anything, but should help narrow things down. If I understand, you're running the LanguageTool server locally? Are you comfortable running curl commands against it so we can see what the server is sending back to the extension?

**Comment by dflock** [comment] 2021-02-12 04:38
> If I understand, you're running the LanguageTool server locally? Are you
comfortable running curl commands against it so we can see what the server
is sending back to the extension?

Yes and yes.

**Comment by davidlday** [comment] 2021-02-12 11:27
Cool. This runs a test against [LanguageTool's test service](https://languagetool.org/http-api/swagger-ui/#!/default/post_check) using en-CA / en-GB as above:

```bash
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'text=Moreover%2C%20the%20street%20is%20almost%20entirely%20residential.%20Moreover%2C%20it%20was%20named%20after%20a%20poet%20This%20is%20spalld%20rong.%20111&language=en-CA&motherTongue=en-GB&enabledOnly=false' 'https://api.languagetoolplus.com/v2/check'
```

Replace the URL at the end with your local service and run, and post results, pls. Thank you!

FYI - I piped the results to `jq` to get a pretty view:

```json
{
  "software": {
    "name": "LanguageTool",
    "version": "5.3-SNAPSHOT",
    "buildDate": "2021-02-08 15:05:09 +0000",
    "apiVersion": 1,
    "premium": true,
    "premiumHint": "You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.",
    "status": ""
  },
  "warnings": {
    "incompleteResults": false
  },
  "language": {
    "name": "English (Canadian)",
    "code": "en-CA",
    "detectedLanguage": {
      "name": "English (US)",
      "code": "en-US",
      "confidence": 0.99
    }
  },
  "matches": [
    {
      "message": "Two successive sentences begin with the same adverb. Consider rewording the sentence or use a thesaurus to find a synonym.",
      "shortMessage": "Two successive sentences begin with the same adverb.",
      "replacements": [],
      "offset": 53,
      "length": 8,
      "context": {
        "text": "... street is almost entirely residential. Moreover, it was named after a poet This is spal...",
        "offset": 43,
        "length": 8
      },
      "sentence": "Moreover, it was named after a poet This is spalld rong.",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "ENGLISH_WORD_REPEAT_BEGINNING_RULE",
        "description": "Successive sentences beginning with the same word",
        "issueType": "style",
        "category": {
          "id": "STYLE",
          "name": "Style"
        },
        "isPremium": false
      },
      "ignoreForIncompleteSentence": true,
      "contextForSureMatch": -1
    },
    {
      "message": "Possible spelling mistake found.",
      "shortMessage": "Spelling mistake",
      "replacements": [
        {
          "value": "spelled"
        },
        {
          "value": "Sally"
        },
        {
          "value": "small"
        },
        {
          "value": "Small"
        },
        {
          "value": "spell"
        },
        {
          "value": "shall",
          "shortDescription": "a verb"
        },
        {
          "value": "sealed"
        },
        {
          "value": "spells"
        },
        {
          "value": "spaced"
        },
        {
          "value": "scaled"
        }
      ],
      "offset": 97,
      "length": 6,
      "context": {
        "text": "...over, it was named after a poet This is spalld rong. 111",
        "offset": 43,
        "length": 6
      },
      "sentence": "Moreover, it was named after a poet This is spalld rong.",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "MORFOLOGIK_RULE_EN_CA",
        "description": "Possible spelling mistake",
        "issueType": "misspelling",
        "category": {
          "id": "TYPOS",
          "name": "Possible Typo"
        },
        "isPremium": false
      },
      "ignoreForIncompleteSentence": false,
      "contextForSureMatch": 0
    },
    {
      "message": "Possible spelling mistake found.",
      "shortMessage": "Spelling mistake",
      "replacements": [
        {
          "value": "song"
        },
        {
          "value": "long"
        },
        {
          "value": "Long"
        },
        {
          "value": "ring"
        },
        {
          "value": "wrong"
        },
        {
          "value": "Wong"
        },
        {
          "value": "rang"
        },
        {
          "value": "Cong"
        },
        {
          "value": "Yong"
        },
        {
          "value": "Kong"
        }
      ],
      "offset": 104,
      "length": 4,
      "context": {
        "text": "...t was named after a poet This is spalld rong. 111",
        "offset": 43,
        "length": 4
      },
      "sentence": "Moreover, it was named after a poet This is spalld rong.",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "MORFOLOGIK_RULE_EN_CA",
        "description": "Possible spelling mistake",
        "issueType": "misspelling",
        "category": {
          "id": "TYPOS",
          "name": "Possible Typo"
        },
        "isPremium": false
      },
      "ignoreForIncompleteSentence": false,
      "contextForSureMatch": 0
    }
  ]
}
```

**Comment by dflock** [comment] 2021-02-15 05:47
I ran this:

```
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'text=Moreover%2C%20the%20street%20is%20almost%20entirely%20residential.%20Moreover%2C%20it%20was%20named%20after%20a%20poet%20This%20is%20spalld%20rong.%20111&language=en-CA&motherTongue=en-GB&enabledOnly=false' 'http://localhost:28081/v2/check' | jq
```

and my output is pretty similar to yours and has suggested fixes in it:

```json
{
  "software": {
    "name": "LanguageTool",
    "version": "5.2",
    "buildDate": "2020-12-29 15:54",
    "apiVersion": 1,
    "premium": false,
    "premiumHint": "You might be missing errors only the Premium version can find. Contact us at support<at>languagetoolplus.com.",
    "status": ""
  },
  "warnings": {
    "incompleteResults": false
  },
  "language": {
    "name": "English (Canadian)",
    "code": "en-CA",
    "detectedLanguage": {
      "name": "English (US)",
      "code": "en-US",
      "confidence": 0.99999756
    }
  },
  "matches": [
    {
      "message": "Two successive sentences begin with the same adverb. Consider rewording the sentence or use a thesaurus to find a synonym.",
      "shortMessage": "Two successive sentences begin with the same adverb.",
      "replacements": [],
      "offset": 53,
      "length": 8,
      "context": {
        "text": "... street is almost entirely residential. Moreover, it was named after a poet This is spal...",
        "offset": 43,
        "length": 8
      },
      "sentence": "Moreover, it was named after a poet This is spalld rong.",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "ENGLISH_WORD_REPEAT_BEGINNING_RULE",
        "description": "Successive sentences beginning with the same word",
        "issueType": "style",
        "category": {
          "id": "STYLE",
          "name": "Style"
        }
      },
      "ignoreForIncompleteSentence": true,
      "contextForSureMatch": -1
    },
    {
      "message": "Possible spelling mistake found.",
      "shortMessage": "Spelling mistake",
      "replacements": [
        {
          "value": "small"
        },
        {
          "value": "shall",
          "shortDescription": "a verb"
        },
        {
          "value": "spell"
        },
        {
          "value": "sealed"
        },
        {
          "value": "spelled"
        },
        {
          "value": "spells"
        },
        {
          "value": "Sally"
        },
        {
          "value": "Small"
        },
        {
          "value": "scaled"
        },
        {
          "value": "spaced"
        },
        {
          "value": "spared"
        },
        {
          "value": "stall"
        },
        {
          "value": "stalled"
        },
        {
          "value": "stalls"
        },
        {
          "value": "salad"
        },
        {
          "value": "spill"
        },
        {
          "value": "spilled"
        },
        {
          "value": "spills"
        },
        {
          "value": "pall"
        },
        {
          "value": "sally"
        },
        {
          "value": "paled"
        },
        {
          "value": "pallid"
        },
        {
          "value": "spayed"
        },
        {
          "value": "pally"
        },
        {
          "value": "scald"
        },
        {
          "value": "palls"
        },
        {
          "value": "smalls"
        },
        {
          "value": "palled"
        },
        {
          "value": "spaded"
        },
        {
          "value": "staled"
        },
        {
          "value": "SIALLE"
        },
        {
          "value": "SPAD"
        }
      ],
      "offset": 97,
      "length": 6,
      "context": {
        "text": "...over, it was named after a poet This is spalld rong. 111",
        "offset": 43,
        "length": 6
      },
      "sentence": "Moreover, it was named after a poet This is spalld rong.",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "MORFOLOGIK_RULE_EN_CA",
        "description": "Possible spelling mistake",
        "issueType": "misspelling",
        "category": {
          "id": "TYPOS",
          "name": "Possible Typo"
        }
      },
      "ignoreForIncompleteSentence": false,
      "contextForSureMatch": 0
    },
    {
      "message": "Possible spelling mistake found.",
      "shortMessage": "Spelling mistake",
      "replacements": [
        {
          "value": "long"
        },
        {
          "value": "ring"
        },
        {
          "value": "song"
        },
        {
          "value": "Kong"
        },
        {
          "value": "Long"
        },
        {
          "value": "wrong"
        },
        {
          "value": "Wong"
        },
        {
          "value": "rang"
        },
        {
          "value": "Cong"
        },
        {
          "value": "Yong"
        },
        {
          "value": "gong"
        },
        {
          "value": "pong"
        },
        {
          "value": "rung"
        },
        {
          "value": "bong"
        },
        {
          "value": "prong"
        },
        {
          "value": "tong"
        },
        {
          "value": "RNG"
        },
        {
          "value": "Ron"
        },
        {
          "value": "Hong"
        },
        {
          "value": "ONG"
        },
        {
          "value": "Roeg"
        },
        {
          "value": "dong"
        }
      ],
      "offset": 104,
      "length": 4,
      "context": {
        "text": "...t was named after a poet This is spalld rong. 111",
        "offset": 43,
        "length": 4
      },
      "sentence": "Moreover, it was named after a poet This is spalld rong.",
      "type": {
        "typeName": "Other"
      },
      "rule": {
        "id": "MORFOLOGIK_RULE_EN_CA",
        "description": "Possible spelling mistake",
        "issueType": "misspelling",
        "category": {
          "id": "TYPOS",
          "name": "Possible Typo"
        }
      },
      "ignoreForIncompleteSentence": false,
      "contextForSureMatch": 0
    }
  ]
}
```

**Comment by dflock** [comment] 2021-02-15 05:56
I just checked the VSCode developer tools console - and nothing shows up in there when I save a document/ trigger spell checking.

**Comment by dflock** [comment] 2021-03-30 14:24
So, this seems to have fixed itself at some point.

Everything has updated and been restarted lots of times, so probably that? Currently, running:

```
Version: 1.55.0-insider
Commit: c71be15869a673c5ed7bfd3fe171757d2ba48142
Date: 2021-03-30T01:55:43.480Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-70-generic
```

along with the latest version of this plugin, and LanguageTool 5.3

I did not check this after each of the many update/restarts, so I don't know what fixed things, sorry!

**Comment by dflock** [comment] 2021-04-01 04:29
Actually, no it hasn't! What happened was, I was editing a Markdown document, where this appears to work fine. When I edit a AsciiDoc document, it sends the text to LanguageTool & marks errors, but doesn't provide suggestions/fixes (as described above) - i.e. it doesn't work properly.

Do, works properly with Markdown, doesn't work with AsciiDoc or plain text documents.

I have the following plugin setting set:

![image](https://user-images.githubusercontent.com/47756/113243460-e9feaa80-9267-11eb-8655-14aa341581db.png)

**Comment by davidlday** [comment] 2021-04-01 17:17
@dflock - thanks for narrowing it down. I'll reproduce and follow up, hopefully with a fix, later today or tomorrow.

**Comment by davidlday** [comment] 2021-04-02 00:36
I've verified / reproduced successfully! Opened issue #284 and closing this again to track separately from the original issue here.

**Closed by davidlday** 2021-04-02 00:36 UTC
Labels: bug
