### ISSUE TITLE
Markdown type styles throw exception

### ISSUE THREAD

**Issue by jseto** [davidlday/vscode-languagetool-linter#69] opened 2019-12-24 11:48 UTC
Markdown text decorated with _, __, *, ** to produce _italic_ or __bold__ text will throw an error (StatusCodeError: 500).

Here is the markdown failing 

```
This is a **bold** style and this is *italic* style using * char

This is a __bold__ style and this is _italic_ style using _ char
```

You can reproduce the error with every service type.

I also realized that there is no test case for font style

**Comment by davidlday** [comment] 2019-12-24 14:37
@jseto - Can you add a screenshot of the error, please? I'm assuming it's in the "LanguageTool Linter" output channel, correct? As of now, I'm unable to recreate the error using your text above verbatim as a test case.

**Comment by jseto** [comment] 2019-12-24 15:56
I've been doing some more research as you couldn't reproduce the error. I tried to reproduce with the test case I proposed and working to me as well.

What I found is that it has to be and spelling error before the type style is set in other to provoke the exception.  

Here is the screen capture with the failure

![Screenshot from 2019-12-24 16-45-21](https://user-images.githubusercontent.com/748604/71418866-198a3480-266d-11ea-826b-bbab359817d9.png)

and this is the capture when the spell error prior to set italic fixed

![Screenshot from 2019-12-24 16-45-46](https://user-images.githubusercontent.com/748604/71419118-265b5800-266e-11ea-981b-a94b6a8f464a.png)

Thanks for your kick answer and have a Merry XMas

**Comment by jseto** [comment] 2019-12-24 16:00
Actually it is not when the spell error is before. It happens when the spell error in the same sentence or paragraph.

**Comment by davidlday** [comment] 2019-12-24 17:36
Merry Xmas to you, too! I'm still not able to reproduce the error when using a locally running LT server, version 4.7. However, I did recreate using the public API, which is running LanguageTool 4.8-SNAPSHOT. 

I have a few more questions:
- What OS are you on, and what version?
- Did you install LanguageTool locally, and if so, what version? Stick with 4.7 if possible.
- If you didn't install locally, can you try to do so?

The rest of this is for capturing and reproducing the situation.

To reproduce, use the following curl command:

```bash
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'data=%7B%20%20%20%22annotation%22%3A%20%5B%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22%23%20%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%23%20%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%200%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%202%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22Bold%20and%20Italics%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%202%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2018%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22%5Cn%5Cn%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%5Cn%5Cn%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2018%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2020%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22This%20is%20a%20%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2020%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2030%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22**%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2030%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2032%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22bold%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2032%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2036%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22**%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2036%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2038%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22%20style%20and%20this%20is%20%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2038%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2057%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22*%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2057%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2058%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22italic%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2058%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2064%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22*%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2064%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2065%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22%20style%20using%20*%20char%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2065%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2084%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22%5Cn%5Cn%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%5Cn%5Cn%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2084%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2086%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22This%20is%20a%20%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2086%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2096%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22__%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2096%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%2098%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22bold%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%2098%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20102%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22__%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20102%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20104%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22%20style%20and%20ths%20is%20%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20104%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20122%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22_%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20122%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20123%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22italic%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20123%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20129%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22_%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20129%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20130%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22%20style%20using%20_%20char%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20130%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20149%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22%5Cn%5Cn%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%5Cn%5Cn%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20149%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20151%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22text%22%3A%20%22This%2C%20even%20misspeled%2C%20will%20not%20fail%20when%20above%20fixed%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20151%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20203%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%2C%20%20%20%20%20%7B%20%20%20%20%20%20%20%22markup%22%3A%20%22%5Cn%22%2C%20%20%20%20%20%20%20%22interpretAs%22%3A%20%22%5Cn%22%2C%20%20%20%20%20%20%20%22offset%22%3A%20%7B%20%20%20%20%20%20%20%20%20%22start%22%3A%20203%2C%20%20%20%20%20%20%20%20%20%22end%22%3A%20204%20%20%20%20%20%20%20%7D%20%20%20%20%20%7D%20%20%20%5D%20%7D&language=en-GB&enabledOnly=false' 'https://languagetool.org/api/v2/check'
```

And here's the original annotated text that causes the error in 4.8-SNAPSHOT only - test using the [LanguageTool Public API](https://languagetool.org/http-api/swagger-ui/#/default):

```json
{
  "annotation": [
    {
      "markup": "# ",
      "interpretAs": "# ",
      "offset": {
        "start": 0,
        "end": 2
      }
    },
    {
      "text": "Bold and Italics",
      "offset": {
        "start": 2,
        "end": 18
      }
    },
    {
      "markup": "\n\n",
      "interpretAs": "\n\n",
      "offset": {
        "start": 18,
        "end": 20
      }
    },
    {
      "text": "This is a ",
      "offset": {
        "start": 20,
        "end": 30
      }
    },
    {
      "markup": "**",
      "interpretAs": "",
      "offset": {
        "start": 30,
        "end": 32
      }
    },
    {
      "text": "bold",
      "offset": {
        "start": 32,
        "end": 36
      }
    },
    {
      "markup": "**",
      "interpretAs": "",
      "offset": {
        "start": 36,
        "end": 38
      }
    },
    {
      "text": " style and this is ",
      "offset": {
        "start": 38,
        "end": 57
      }
    },
    {
      "markup": "*",
      "interpretAs": "",
      "offset": {
        "start": 57,
        "end": 58
      }
    },
    {
      "text": "italic",
      "offset": {
        "start": 58,
        "end": 64
      }
    },
    {
      "markup": "*",
      "interpretAs": "",
      "offset": {
        "start": 64,
        "end": 65
      }
    },
    {
      "text": " style using * char",
      "offset": {
        "start": 65,
        "end": 84
      }
    },
    {
      "markup": "\n\n",
      "interpretAs": "\n\n",
      "offset": {
        "start": 84,
        "end": 86
      }
    },
    {
      "text": "This is a ",
      "offset": {
        "start": 86,
        "end": 96
      }
    },
    {
      "markup": "__",
      "interpretAs": "",
      "offset": {
        "start": 96,
        "end": 98
      }
    },
    {
      "text": "bold",
      "offset": {
        "start": 98,
        "end": 102
      }
    },
    {
      "markup": "__",
      "interpretAs": "",
      "offset": {
        "start": 102,
        "end": 104
      }
    },
    {
      "text": " style and ths is ",
      "offset": {
        "start": 104,
        "end": 122
      }
    },
    {
      "markup": "_",
      "interpretAs": "",
      "offset": {
        "start": 122,
        "end": 123
      }
    },
    {
      "text": "italic",
      "offset": {
        "start": 123,
        "end": 129
      }
    },
    {
      "markup": "_",
      "interpretAs": "",
      "offset": {
        "start": 129,
        "end": 130
      }
    },
    {
      "text": " style using _ char",
      "offset": {
        "start": 130,
        "end": 149
      }
    },
    {
      "markup": "\n\n",
      "interpretAs": "\n\n",
      "offset": {
        "start": 149,
        "end": 151
      }
    },
    {
      "text": "This, even misspeled, will not fail when above fixed",
      "offset": {
        "start": 151,
        "end": 203
      }
    },
    {
      "markup": "\n",
      "interpretAs": "\n",
      "offset": {
        "start": 203,
        "end": 204
      }
    }
  ]
}
```

**Comment by jseto** [comment] 2019-12-24 18:35
I installed LanguageTool 4.7 (I had 4.8SNAPSHOT in local machine) and everything looks working OK in managed service type.

FYI. I run Ubuntu 18.04.3 LTS
I was able to reproduce errors in managed and public service types.

both tests you propose (curl and API) fail from my machine as expected

Now, with 4.7 ver. I got annoying messages in the output console about empty parameter set.

**Comment by davidlday** [comment] 2019-12-24 18:53
I'll get my Ubuntu laptop out and see if I can reproduce this "empty parameter" error, but I may not get to it until Thursday at this point. It almost looks like the API is being hit from a web browser.

Out of curiosity, how are you installing LanguageTool? Are you just manually downloading it, or are you using a package manager (apt, brew, etc)? I like to capture the different ways folks are installing LanguageTool in the wiki whenever possible.

**Comment by jseto** [comment] 2019-12-25 23:15
Yes. It was my web browser trying to hit my gatsby develop server.

I've been looking for a way to set a different port but not been able to find.

Answering your question; I installed ver 4.8SNAPSHOT with `snap` and ver. 4.7 downloading the zip file and installed manually.

I've been using LanguageTool for a while but on Atom editor (moving these days to vscode), Libreoffice and Chrome extension.

Hope this helps

**Comment by jseto** [comment] 2019-12-25 23:50
I think you should put a link in the readme file to the wiki. There is good info there that can be useful to other people and is not obvious to go to the wiki to find more info. Mainly because many projects do not use it.

On the other hand, in my modest opinion, you should set the default to the public service type. This is a sure bet to install and work. If you ask people to install more things other than the extension itself, they are likely to refuse to do it. Let them try in the easy way and, after they are happy, move to more sophisticated and functional options.

**Comment by davidlday** [comment] 2019-12-27 22:36
Thanks for the suggestions. I have an issue opened for updating the docs, so I'll note your ideas over there. Closing this as it appears the LanguageTool developers have fixed the issue.

**Closed by davidlday** 2019-12-27 22:37 UTC
