### ISSUE TITLE
Unwanted Asturian rules applied on the check.

### ISSUE THREAD

**Issue by PabloLION** [davidlday/vscode-languagetool-linter#624] opened 2023-08-03 11:29 UTC
**Describe the bug**
I wrote `ANCHOR_X=49` and it shows 
`Atopáu un posible fallu d'ortografía LanguageTool (MORFOLOGIK_RULE_AST)`
![image](https://github.com/davidlday/vscode-languagetool-linter/assets/36828324/625dbd0f-e355-446f-be5b-39d11607fbfd)
which means "Found a possible error of orthography.
This happened while I didn't enable anything about Asturian ([NOT Austrian](https://en.wikipedia.org/wiki/Asturian_language)) on my PC.

**To Reproduce**
1. Create a new plaintext file, in my case I had `.env` file.
2. Write `ANCHOR_X=49`
3. See error

**Expected behavior**
To not show Asturian grammar check.

**Screenshots**
Same as above
![image](https://github.com/davidlday/vscode-languagetool-linter/assets/36828324/625dbd0f-e355-446f-be5b-39d11607fbfd)

**Environment & Configuration (please complete the following information):**
 - OS + Version: Windows 10
 - VS Code Version: 1.81.0-insider
 - LanguageTool Linter Version: v0.20.0
 - LanguageTool Version: I don't know
 - Service Configuration: public
 - Service Classpath (if 'managed'): N/A

**Additional context**
Today is the first time it happened and presumably it can be caused by the Language Tool upgrade?
I see that this page <https://community.languagetool.org/rule/show/MORFOLOGIK_RULE_AST?lang=ast> got a new snapshot at
> SNAPSHOT (2023-08-02 20:33:02 +0000)

**Comment by davidlday** [comment] 2023-08-10 09:41
Thanks for opening this issue. Can you please tell me what you have for the following settings:

* Language Tool Linter > Language Tool: Language
* Language Tool Linter > Language Tool: Mother Tongue
* Language Tool Linter > Language Tool: Preferred Variants

And can you also attach a complete copy of the document, if possible?

I suspect Language is set to "auto" (the default), in which case LanguageTool will try to guess what language the document is and respond accordingly. Thank you!

**Comment by PabloLION** [comment] 2023-11-19 03:27
@davidlday Sorry for the late response, I just saw your response today. Your assumption was totally correct, I guess it's caused by `LanguageTool` server hence I guess for the extension, there's nothing to fix. In this case, maybe closing this issue is better?

Here are my settings:
![image](https://github.com/davidlday/vscode-languagetool-linter/assets/36828324/901100cb-5dc6-4ac9-b425-d2d12e4158b7)

**Comment by davidlday** [comment] 2023-11-19 12:43
No worries! Thanks for confirming the cause. Will close this out now.

**Closed** 2023-11-19 12:44 UTC
Labels: bug
